### ISSUE TITLE
Checklist for 2.2

### ISSUE THREAD

**Issue by Bara20** [Bara20/TroubleinTerroristTown#138]
Since a few new features, fixes and other changes, it's time to update the version to 2.2.X.

Here's a list of stuff that need a test:
- [x] Shop (incl. detective and traitor items)
- [x] Glow
- [x] Wallhack
- [x] TA-Grenade
- [x] SilentAWP
- [x] Knockout
- [x] Camera and Drones
- [ ] Damage before a round started
- [ ] Damage after a round ended
- [x] Translations

**Comment by omar-damaj** [comment]
SilentAWP works as far as I can see. At first it was glitchy where you can pick up any AWP on the map and it would be silent but now it is good. 
For the Knockout, It drops a body under you but there is 2 copies of the body. See screenshot for example: http://i.imgur.com/Cy3EjAg.jpg

**Comment by Bara20** [comment]
@omar-damaj Could you try this commit ? https://github.com/Bara20/TroubleinTerroristTown/commit/9233db9282dc8a48a698d56b3e29d1813ddacf03

**Comment by omar-damaj** [comment]
Knockout is all good now! Thank you @Bara20 
Maybe one improvement is to see if it is possible to stop the taser from being used as an ID taser (like the detective taser that says the roles of the person in chat).
